### ISSUE TITLE
How to set candidate group when a new user task is created?

### ISSUE THREAD

**Issue by justshot** [camunda-community-hub/zeebe-simple-tasklist#172] opened 2023-05-11 00:35 UTC
Hi,

For each user task, I have predefined a list of candidate groups. The is to enforce that only the user belong to the candidate group can claim and complete the task.
How can I set the candidate group once the user task is created?

**Comment by saig0** [comment] 2023-05-16 04:41
Candidate groups should work in general. If a user task defines a candidate group, the task is only visible to users that are assigned to a group with the same name.

> How can I set the candidate group once the user task is created?

This is not possible. It is not a limitation of Zeebe-Simple-Tasklist but of Zeebe itself. You can't change the properties of the user task after it is created. 

To change a property, the process must leave the user task first and enter it again (i.e. loop back). 

Does this help you?

**Comment by justshot** [comment] 2023-05-16 12:51
> Candidate groups should work in general. If a user task defines a candidate group, the task is only visible to users that are assigned to a group with the same name.
> 
> > How can I set the candidate group once the user task is created?
> 
> This is not possible. It is not a limitation of Zeebe-Simple-Tasklist but of Zeebe itself. You can't change the properties of the user task after it is created.
> 
> To change a property, the process must leave the user task first and enter it again (i.e. loop back).
> 
> Does this help you?

Thanks for replying. I think my question mislead you. The issue I encountered is that the **Candidate groups** for a user task in a process definition does not work. Refer to user task "Approve" of this  [process definition](https://modeler.cloud.camunda.io/share/a5810621-c43e-46a2-b52e-4e0f4f0226c4)

When debuging `UserTaskJobHandler#readCandidateGroups`, I find out both custom header `io.camunda.zeebe:candidateGroups` and variable `candidateGroups` are null.

**Comment by saig0** [comment] 2023-05-17 09:21
@justshot I can't reproduce the behavior with the given process. 

I see that the user task has the candidate groups `auditor`. 

![image](https://github.com/camunda-community-hub/zeebe-simple-tasklist/assets/4305769/774c13a3-1122-4849-a036-b15a34a1f6d9)

If I switch to tasklist (version `1.1.0`) and assign my user to the group `auditor` then I can see the user task in the list. 

Which version of tasklist do you use?

**Comment by justshot** [comment] 2023-05-19 03:03
I switched to below version:
**docker**: [ghcr.io/camunda-community-hub/zeebe-with-hazelcast-exporter:8.2.0](http://ghcr.io/camunda-community-hub/zeebe-with-hazelcast-exporter:8.2.0)
**local Java env**: zeebe-simple-tasklist:1.1.0

After I deployed my simple bpmn, the deployment is success with log: 
`Started instance for processDefinitionKey='2251799813685290', bpmnProcessId='simple-approve', version='2' with processInstanceKey='2251799813685292'
`

**Comment by saig0** [comment] 2023-05-24 09:19
@justshot it seems that the app can't connect to Hazelcast. 

Could you use the [docker-compose.yml](https://github.com/camunda-community-hub/zeebe-simple-tasklist/blob/main/docker/docker-compose.yml) file to reproduce the behavior? Note that you would need to update the versions first.

**Comment by justshot** [comment] 2023-05-26 22:38
@saig0 Using the [docker-compose.yml](https://github.com/camunda-community-hub/zeebe-simple-tasklist/blob/main/docker/docker-compose.yml solved the problem). I will close the question. Thank you!

**Closed** 2023-05-26 22:39 UTC
Labels: question
